name: simple_grinder
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
# author: terrasea <email@example.com>


dependencies:
  build_runner: ^0.10.0
  build_test: ^0.10.2
  build_web_compilers: ^0.4.0
  grinder: any
  dart_style: any
#  path: ^1.4.1

dev_dependencies:
  test: any
  mockito: any
#  bwu_grinder_tasks: ^0.2.0-dev.0

